#!/bin/bash
# shellcheck disable=SC1090


function chcreds() {
    local creds
    if ! creds=$(oscreds "$@"); then
        echo "Failed to load credentials" >&2
        return 1
    fi
    source <(printf '%s\n' "$creds")
    echo "Credentials loaded for $OS_CRED"
}

function recred() {
    if [ -n "$OS_CRED" ]; then
        chcreds $OS_CRED
    else
        chcreds
    fi
}

function rmcreds() {
    for v in $(env | grep -E '^OS_' | sed 's/=.*//'); do
      unset "$v"
    done
}

function prcreds {
    env | awk -F'[=_]' '/^OS_/ {if ($2 == "PASSWORD" || $2 == "TOKEN") print "OS_"$2"=******" ; else print $0}'
}

# Function useful for adding to your bash prompt
function os_creds {
    [ -z "$OS_CRED" ] || echo " $OS_CRED"
}

# vim:syntax=sh
