name: Build oscreds

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          - os: ubuntu-latest
            goos: linux
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GPGME dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get autopurge -y needrestart
          sudo apt-get install -y libgpgme-dev pkg-config

      - name: Install GPGME dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install gpgme

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build oscreds
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -o oscreds-${{ matrix.goos }}-${{ matrix.goarch }} ./...

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: oscreds-${{ matrix.goos }}-${{ matrix.goarch }}
          path: oscreds-${{ matrix.goos }}-${{ matrix.goarch }}
