name: Build oscreds

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          - os: ubuntu-24.04-arm
            goos: linux
            goarch: arm64
          - os: macos-latest
            goos: darwin
            goarch: arm64
          - os: macos-15-intel
            goos: darwin
            goarch: amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set version
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "VERSION=1.0.${{ github.run_number }}-${SHORT_SHA}" >> $GITHUB_ENV

      - name: Build oscreds
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -o oscreds-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.VERSION }} ./...

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: oscreds-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.VERSION }}
          path: oscreds-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.VERSION }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Set version
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "VERSION=1.0.${{ github.run_number }}-${SHORT_SHA}" >> "$GITHUB_ENV"

      - name: Set changelog
        run: |
          {
            echo "CHANGELOG<<EOF"
            git log -1 --pretty=format:'%s'
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Create GitHub Release
        env:
          VERSION: ${{ env.VERSION }}
          CHANGELOG: ${{ env.CHANGELOG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$VERSION" ./artifacts/*/* \
            --title "Release $VERSION" \
            --notes "$CHANGELOG"
